name: Update Dependencies

on:
  schedule:
    - cron: '0 * * * *' # Toutes les heures

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: npm update

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update dependencies"
          git push
