name: Update Dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '01 * * * *' # Toutes les heures

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
        
      - name: Update dependencies
        run: npm update

      - name: Run SonarQube analysis
        run: npm install -g sonarqube-scanner
             sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
