name: Update Dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '01 * * * *' # Toutes les heures

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Update dependencies
        run: npm update

      - name: Build
        run: npm install gulp
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
